# REGISTRY_HOST='HOST:PORT' envsubst < cm-insecure-registries-pink.yaml | kubectl apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: insecure-registries-pink
data:
  100-insecure-registries-pink.conf: |
    # https://www.redhat.com/sysadmin/manage-container-registries
    unqualified-search-registries = ["docker.io"]
    [[registry]]
    location="$REGISTRY_HOST"
    insecure=true
